### ISSUE TITLE
Front-end should recognize, log, and react to errors

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/multiplayer-phone-game#27] opened 2018-11-14 19:15 UTC
1.  Front-end application recognizes when it errors
2.  Logging error to file
3.  On error, refresh the browser. 

This might be able to be handled through an Electron Wrapper api

**Comment by bryankennedy** [comment] 2019-03-08 18:20
This is a dupe of #28 and we've got it covered in Stele. Closing this one.

**Closed by bryankennedy** 2019-03-08 18:20 UTC
Labels: duplicate
